"""empty message

Revision ID: 0d997d1ee9c2
Revises: 58374363cec3
Create Date: 2024-07-04 11:42:23.480703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d997d1ee9c2'
down_revision = '58374363cec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_users_name', ['name'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_name', type_='unique')
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('username')
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
